# Generated by Django 4.1.1 on 2022-09-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_doctor',
        ),
    ]
