# Generated by Django 4.1.1 on 2022-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0002_remove_customuser_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_Type',
            field=models.CharField(choices=[('HOSADMIN', 'HOSADMIN'), ('DOCTOR', 'DOCTOR'), ('PATIENT', 'PATIENT')], default='NULL', max_length=10),
        ),
    ]
