# Generated by Django 4.1.1 on 2022-10-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='user/profilepic/'),
        ),
    ]
