# Generated by Django 4.1.1 on 2022-10-18 06:24

from django.db import migrations, models
import userSystem.storage


class Migration(migrations.Migration):

    dependencies = [
        ('userSystem', '0005_customuser_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilepic',
            field=models.ImageField(default='user/profilepic/default.svg', null=True, storage=userSystem.storage.OverwriteStorage(), upload_to='user/profilepic/'),
        ),
    ]
