# Generated by Django 4.1.1 on 2022-10-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospital_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladmin',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
