# Generated by Django 4.1.1 on 2022-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospitaladmin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpatient',
            name='documents',
            field=models.FileField(null=True, upload_to='hospital/prescription'),
        ),
        migrations.AlterField(
            model_name='bookingpatient',
            name='state',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('PENDING', 'PENDING'), ('DELETED', 'DELETED')], max_length=20, null=True),
        ),
    ]
