# Generated by Django 4.1.1 on 2022-10-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_bookingpatient_documents_alter_bookingpatient_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingpatient',
            name='documents',
        ),
    ]
