# Generated by Django 4.1.1 on 2022-10-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_remove_bookingpatient_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpatient',
            name='documents',
            field=models.FileField(null=True, upload_to='hospital/prescription'),
        ),
    ]
