# Generated by Django 4.1.1 on 2022-10-18 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_hospital_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='createdBy',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaladmin'),
        ),
    ]
