# Generated by Django 4.1.1 on 2022-10-18 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_hospital_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitaladmin'),
        ),
    ]
