# Generated by Django 4.1.1 on 2022-10-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_hospital_createdby'),
        ('doctor', '0004_doctorlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorlist',
            old_name='doctorID',
            new_name='doctorName',
        ),
        migrations.RenameField(
            model_name='doctorlist',
            old_name='hospitalID',
            new_name='hospitalName',
        ),
        migrations.AlterUniqueTogether(
            name='doctorlist',
            unique_together={('doctorName', 'hospitalName')},
        ),
    ]
